services:
  app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - auth_network

  database:
    image: postgres:17-alpine
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - auth_network
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "auth_service"

  tests:
    build: .
    command: bash -c "pip install -r requirements.dev.txt && pytest -v"
    environment:
      CONFIG_FILE_NAME: config.test.yaml
    networks:
      - auth_network
    depends_on:
      - database

volumes:
  auth_db_data:

networks:
  auth_network: